# Generated by Django 3.2.25 on 2024-05-16 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_post', models.CharField(max_length=255)),
                ('state_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('country_pos', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=255)),
                ('manager_addr', models.TextField()),
                ('manager_city', models.CharField(max_length=255)),
                ('manager_phon', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_addr', models.TextField()),
                ('owner_city', models.CharField(max_length=255)),
                ('owner_phon', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Owner',
            },
        ),
        migrations.CreateModel(
            name='RegionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'RegionCode',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Type',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.location')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.manager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.owner')),
                ('region_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.regioncode')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.type')),
            ],
            options={
                'db_table': 'Airport',
            },
        ),
    ]
