# Generated by Django 3.2.25 on 2024-05-02 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=255)),
                ('manager_addr', models.TextField()),
                ('manager_city', models.CharField(max_length=255)),
                ('manager_phon', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_addr', models.TextField()),
                ('owner_city', models.CharField(max_length=255)),
                ('owner_phon', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Owner',
            },
        ),
        migrations.CreateModel(
            name='ReferencePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_point_1', models.CharField(default='', max_length=255)),
                ('ref_point_2', models.CharField(default='', max_length=255)),
                ('ref_point_3', models.CharField(default='', max_length=255)),
                ('ref_point_4', models.CharField(default='', max_length=255)),
            ],
            options={
                'db_table': 'ReferencePoint',
            },
        ),
        migrations.CreateModel(
            name='RegionCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'RegionCode',
            },
        ),
        migrations.CreateModel(
            name='SiteNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_number', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'SiteNumber',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Type',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('jet_count', models.IntegerField()),
                ('helicopter_count', models.IntegerField()),
                ('military_aircraft_count', models.IntegerField()),
                ('commercial_aircraft_count', models.IntegerField()),
                ('flight_count', models.IntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.location')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.manager')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.owner')),
                ('reference_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.referencepoint')),
                ('region_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.regioncode')),
                ('site_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.sitenumber')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baza_v1.type')),
            ],
            options={
                'db_table': 'Airport',
            },
        ),
    ]
