# Generated by Django 3.2.25 on 2024-04-19 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='airport',
            table='Airport',
        ),
        migrations.AlterModelTable(
            name='basedaircraft',
            table='BasedAircraft',
        ),
        migrations.AlterModelTable(
            name='manager',
            table='Manager',
        ),
        migrations.AlterModelTable(
            name='owner',
            table='Owner',
        ),
        migrations.AlterModelTable(
            name='referencepoint',
            table='ReferencePoint',
        ),
    ]
