# Generated by Django 3.2.25 on 2024-04-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_v1', '0003_auto_20240419_2102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasedAircraft',
        ),
    ]
